server:
  port: 8080
  tomcat:
    accept-count: 1000
    max-connections: 20000
    connection-timeout: 30000

spring:
  profiles:
    active: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      validation-query: select 1
      validation-query-timeout: 5000
      initial-size: 100
      max-active: 2000
      min-idle: 100
      max-wait: 60000
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      stat-view-servlet:
        allow: ""
        deny: ""
        reset-enable: false
        enabled: true
        login-username: dsj
        login-password: 1qaz@WSX
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*'
        session-stat-enable: true
        session-stat-max-count: 10
      filter:
        wall:
          config:
            none-base-statement-allow: true
            multi-statement-allow: true
  http:
    jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      default-property-inclusion: NON_NULL
      time-zone: GMT+8
  main:
    allow-bean-definition-overriding: true

mybatis-plus:
  mapperPackage: com.jyd.mapper
  mapperLocations: com.jyd.mapper/xml/*Mapper.xml
  typeAliasesPackage: com.jyd.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
