spring:
  datasource:
    dynamic:
      primary: master
      strict: false
      datasource:
        master:
          url: jdbc:mysql://172.16.10.243:3306/jydboot?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&autoReconnect=true&rewriteBatchedStatements=true&allowMultiQueries=true
          username: root
          password: Whdsj@!db109
          driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 172.16.10.243
    port: 6379
    password: 'Whdsj@Wcyj109'
    database: 10
    ssl: false
  rabbitmq:
    host: 172.16.10.249
    port: 5672
    username: root
    password: Wcyj@mq0214
    virtual-host: /jydboot
xxl:
  job:
    accessToken: 'bc6fea25a4534119aeba45af7d7b68d9'
    admin:
      addresses: http://127.0.0.1:9998/xxl-job-admin
    executor:
      address: ''
      appname: xxl-job-executor-sample
      ip: ''
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: 30
      port: 9999
minio:
  endpoint: http://127.0.0.1:9000
  accessKey: admin
  secretKey: Dsj*123456
  bucketName: jydboot

knife4j:
  production: false
